name: AutoOp
main: com.no32ks.nobackdoors.Main
version: 2.0
author: <your IGN or name>
commands:
   basic:
      description: This is a demo command.
      usage: /<command> [player]
      permission: <plugin name>.basic
      permission-message: You don't have <permission>